# Generated by Django 5.2.7 on 2025-10-25 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bottoms',
            name='sizes',
            field=models.CharField(choices=[('s', 's'), ('m', 'm'), ('l', 'l'), ('xl', 'xl'), ('xxl', 'xxl'), ('xxxl', 'xxxl'), ('none', 'No Size')], max_length=50),
        ),
        migrations.AlterField(
            model_name='home',
            name='sizes',
            field=models.CharField(choices=[('s', 's'), ('m', 'm'), ('l', 'l'), ('xl', 'xl'), ('xxl', 'xxl'), ('xxxl', 'xxxl'), ('none', 'No Size')], max_length=50),
        ),
        migrations.AlterField(
            model_name='sets',
            name='sizes',
            field=models.CharField(choices=[('s', 's'), ('m', 'm'), ('l', 'l'), ('xl', 'xl'), ('xxl', 'xxl'), ('xxxl', 'xxxl'), ('none', 'No Size')], max_length=50),
        ),
        migrations.AlterField(
            model_name='tops',
            name='sizes',
            field=models.CharField(choices=[('s', 's'), ('m', 'm'), ('l', 'l'), ('xl', 'xl'), ('xxl', 'xxl'), ('xxxl', 'xxxl'), ('none', 'No Size')], max_length=50),
        ),
    ]
