# Generated by Django 5.2.7 on 2025-10-25 16:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_bottoms_sizes_alter_home_sizes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitems',
            name='Bottoms',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='app.bottoms'),
        ),
        migrations.AlterField(
            model_name='cartitems',
            name='Home',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='app.home'),
        ),
        migrations.AlterField(
            model_name='cartitems',
            name='Sets',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='app.sets'),
        ),
        migrations.AlterField(
            model_name='cartitems',
            name='Tops',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='app.tops'),
        ),
        migrations.AlterField(
            model_name='cartitems',
            name='price',
            field=models.DecimalField(decimal_places=2, default=None, max_digits=10),
        ),
    ]
