# Generated by Django 5.2.7 on 2025-10-26 12:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_profile_role'),
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitems',
            name='Bottoms',
        ),
        migrations.RemoveField(
            model_name='cartitems',
            name='Home',
        ),
        migrations.RemoveField(
            model_name='cartitems',
            name='Sets',
        ),
        migrations.RemoveField(
            model_name='cartitems',
            name='Tops',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='Bottoms',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='Home',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='Sets',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='Tops',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='price',
        ),
        migrations.RemoveField(
            model_name='orders',
            name='Bottoms',
        ),
        migrations.RemoveField(
            model_name='orders',
            name='Home',
        ),
        migrations.RemoveField(
            model_name='orders',
            name='Sets',
        ),
        migrations.RemoveField(
            model_name='orders',
            name='Tops',
        ),
        migrations.RemoveField(
            model_name='orders',
            name='address',
        ),
        migrations.RemoveField(
            model_name='orders',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='orders',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='orders',
            name='middle_name',
        ),
        migrations.RemoveField(
            model_name='orders',
            name='phone_number',
        ),
        migrations.RemoveField(
            model_name='orders',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='wishlistitems',
            name='Bottoms',
        ),
        migrations.RemoveField(
            model_name='wishlistitems',
            name='Home',
        ),
        migrations.RemoveField(
            model_name='wishlistitems',
            name='Sets',
        ),
        migrations.RemoveField(
            model_name='wishlistitems',
            name='Tops',
        ),
        migrations.AddField(
            model_name='cartitems',
            name='content_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='cartitems',
            name='object_id',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='checkout',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.checkout'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='content_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='object_id',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='orders',
            name='checkout',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.checkout'),
        ),
        migrations.AddField(
            model_name='orders',
            name='status',
            field=models.CharField(default='Pending', max_length=50),
        ),
        migrations.AddField(
            model_name='wishlistitems',
            name='content_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='wishlistitems',
            name='object_id',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='cartitems',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='orders',
            name='total_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='orders',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL),
        ),
    ]
