# Generated by Django 5.2.7 on 2025-10-26 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_remove_cartitems_bottoms_remove_cartitems_home_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='bottoms',
            field=models.ManyToManyField(blank=True, to='app.bottoms'),
        ),
        migrations.AddField(
            model_name='cart',
            name='home',
            field=models.ManyToManyField(blank=True, to='app.home'),
        ),
        migrations.AddField(
            model_name='cart',
            name='sets',
            field=models.ManyToManyField(blank=True, to='app.sets'),
        ),
        migrations.AddField(
            model_name='cart',
            name='tops',
            field=models.ManyToManyField(blank=True, to='app.tops'),
        ),
        migrations.AddField(
            model_name='wishlist',
            name='bottoms',
            field=models.ManyToManyField(blank=True, to='app.bottoms'),
        ),
        migrations.AddField(
            model_name='wishlist',
            name='home',
            field=models.ManyToManyField(blank=True, to='app.home'),
        ),
        migrations.AddField(
            model_name='wishlist',
            name='sets',
            field=models.ManyToManyField(blank=True, to='app.sets'),
        ),
        migrations.AddField(
            model_name='wishlist',
            name='tops',
            field=models.ManyToManyField(blank=True, to='app.tops'),
        ),
    ]
