# Generated by Django 5.2.7 on 2025-10-26 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_orders_content_type_orders_object_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orders',
            name='checkout',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='checkout',
        ),
        migrations.AddField(
            model_name='orders',
            name='address',
            field=models.CharField(blank=True, max_length=5000),
        ),
        migrations.AddField(
            model_name='orders',
            name='first_name',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='orders',
            name='last_name',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='orders',
            name='middle_name',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='orders',
            name='phone_number',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.DeleteModel(
            name='checkout',
        ),
    ]
