# Generated by Django 5.2.7 on 2025-10-26 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_remove_orders_checkout_remove_orderitem_checkout_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='bottoms',
            field=models.ManyToManyField(blank=True, to='app.bottoms'),
        ),
        migrations.AddField(
            model_name='orders',
            name='home',
            field=models.ManyToManyField(blank=True, to='app.home'),
        ),
        migrations.AddField(
            model_name='orders',
            name='sets',
            field=models.ManyToManyField(blank=True, to='app.sets'),
        ),
        migrations.AddField(
            model_name='orders',
            name='tops',
            field=models.ManyToManyField(blank=True, to='app.tops'),
        ),
    ]
